Algoritmo "Teste de variável"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Thais Leal
// Descrição   : Teste de variável
// Autor(a)    : Wesley Roberty
// Data atual  : 04/09/2024
Var
// Seção de Declarações das variáveis 
 nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nome <-"João"
escreva (nome)
nome <-"Maria"
escreva (nome)
Fimalgoritmo